SmartView
htmlacademy-ecmascript/174891-big-trip-13 pull request #10
Opened 2021-01-21 09:48 UTC by MariaSarbaj

Вроде и работает, но как-то не до конца. Посмотри, пожалуйста, на данном этапе и буду работать дальше

2021-01-22 04:58 UTC, AlexMasterov requested changes
Нужно убрать все комментарии (= `<!-- ` и `//`).

Б18

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +    return super.updateData(update, justDataUpdating);
Реализация потомка `EventEditItem.updateData` полностью дублирует родителя `SmartView.updateData`.

Д11

Нужно удалить.

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
>    _onFormSubmit(evt) {
```
_onFormSubmit
_subscribeOnEvents
```

Д8

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +    const saveButtonTemplate = template.querySelector(`.event__save-btn`);
<details>
<summary>_subscribeOnEvents</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/fe5683595cdb7c6f1e9572abde0f1840889f736b/src/view/event-edit/event-edit-item.js#L129-L132
</details>

```js
template instanceof Element // true
```
Это [`Element`](https://developer.mozilla.org/ru/docs/Web/API/Element), а не шаблон.

Д6

`template` нужно переименовать, а у остальных (с учетом выбора именования по Д6) убрать суффикс `Template`.

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +    return createEditPointTemplate(this._point, this._destinations, this._id);
<details>
<summary>EventEditItem</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/fe5683595cdb7c6f1e9572abde0f1840889f736b/src/view/event-edit/event-edit-item.js#L99

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/fe5683595cdb7c6f1e9572abde0f1840889f736b/src/view/event-edit/event-edit-item.js#L106
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/fe5683595cdb7c6f1e9572abde0f1840889f736b/src/view/event-edit/event-edit-item.js#L11
</details>

`this._id` передается 3-м аргументом, но в `createEditPointTemplate` использует только 2 параметра и это значение не используется.

Б18

createEditPointTemplate(this.\_`point`, this.\_destinations, this.\_id`)

`createEditPointTemplate` может получить `id` из `point`. 
Поэтому передавать `id` отдельно не имеет смысла.

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/create-offers-template.js
> +        <input class="event__offer-checkbox  visually-hidden" id="event-offer-${offers}-${index + 1}" type="checkbox" name="event-offer-${id}"
```js
Array.isArray(offers) // true
```

id="event-offer-${`offers`}"
id="event-offer-`[object Object],[object Object]`-1"

😕

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/smart.js
> +    parent.replaceChild(newElement, prevElement);
<details>
<summary>utils/utils.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/fe5683595cdb7c6f1e9572abde0f1840889f736b/src/utils/utils.js#L49
</details>

<details>
<summary>updateElement</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/fe5683595cdb7c6f1e9572abde0f1840889f736b/src/view/smart.js#L28-L34
</details>

`replaceWith` / `replaceChild`

Д7

Нужно выбрать и использовать один способ (метод).

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/smart.js
> +  updateElement() {
<details>
<summary>updateElement</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/fe5683595cdb7c6f1e9572abde0f1840889f736b/src/view/smart.js#L28
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/fe5683595cdb7c6f1e9572abde0f1840889f736b/src/view/smart.js#L32
</details>

prev`Element` 
new`Element`

Д6

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
>                    <button class="event__save-btn  btn  btn--blue" type="submit">Save</button>
<details>
<summary>markup/add-new-point.html</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/fe5683595cdb7c6f1e9572abde0f1840889f736b/markup/add-new-point.html#L191-L192
</details>
<details>
<summary>markup/edit-point.html</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/fe5683595cdb7c6f1e9572abde0f1840889f736b/markup/edit-point.html#L229-L233
</details>

Сейчас созданные точки маршрута (в режиме _редактирования_) используют разметку формы _создание_ новой точки. У формы нет "стрелки вверх" для сворачивания и вместо кнопки `Delete` кнопка `Cancel`.

Б1

Теперь нужно это доработать.

> Обрати внимание, что разметка формы _создания_ новой карточки и _редактирование_ существующей почти полностью схожи

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
>    _onFormSubmit(evt) {
При нажатие на кнопку `Save` выбрасывается исключение (ошибка):
```
utils.js:62 Uncaught TypeError: Cannot read property 'id' of undefined
```
Б2

Нужно разобраться и исправить.

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +export default class EventEditItem extends SmartView {
См. задание:

> при смене типа точки маршрута нужно показать соответствующий типу набор дополнительных опций

Не реализовано.

> Для этого требуется отдельная структуру всех _доступных_ предложений `offers`

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +export default class EventEditItem extends SmartView {
См. задание:

> при выборе пункта назначения нужно показать новые описание и фотографии

Не реализовано.

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +export default class EventEditItem extends SmartView {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/105447576-83687980-5c85-11eb-9c68-7999fe0801e4.png)

</details>

Выбор и отмена доп. предложение не доступно: по нажатию ничего не происходит.

Нужно разобраться и исправить.

2021-01-22 04:58 UTC, AlexMasterov commented on src/view/event-edit/create-offers-template.js
>      const isChecked = Math.random() > 0.5;
`isChecked`

Для режима редактирования и создания новой точки маршрута нужен _общий_ список всех _доступных_
предложений, с учетом выбранного типа. Такой список потребуется получить с сервера отдельной
структурой (обсуждалось на лекции). Предложения `offers` (в твоем случае) в данных точки маршрута считаются уже _выбранными_ (из общего списка _доступных_).

При редактировании созданной точки маршрута нужно использовать уже _выбранные_ `offers` из
данных самой точки и _доступные_ `offers[type]` из отдельной структуры. При этом предложения из доступного списка не должны дублировать уже выбранные: по названию **и** цене. Могут быть предложения с одинаковым названием, но с разной (рыночной) ценой.

При получение данных с сервера (структуры `offers`) потребуется доработать логику.

2021-01-22 18:24 UTC, MariaSarbaj commented
Получилось исправить часть замечаний. Попробовала создать отдельные структуры для предложений (типа activeOffers и eventOffers), но только все сломала 🤦‍♀️ Нужны пояснения и по тому, как заменять фото и описания, не разобралась с этим, и не разобралась с ошибкой при save  😢

2021-01-25 00:10 UTC, AlexMasterov requested changes

2021-01-25 00:10 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +  _onEventDataChange() {
<details>
<summary>_onEventDataChange</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/bdb6feb9c811d670d9afcbba61cb837fd7ab77ca/src/view/event-edit/event-edit-item.js#L136
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/bdb6feb9c811d670d9afcbba61cb837fd7ab77ca/src/view/event-edit/event-edit-item.js#L147
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/bdb6feb9c811d670d9afcbba61cb837fd7ab77ca/src/view/event-edit/event-edit-item.js#L152
</details>

Б36

Анон. обработчики могут накапливаться.

2021-01-25 00:10 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +    this._onEventDataChange();
`this._onEventDataChange()`

Б10

Метод использует именование обработчика событий DOM, но вызывается напрямую пользовательском коде.

2021-01-25 00:10 UTC, AlexMasterov commented on src/presenter/point.js
>      this._eventView.setOnFavoriteButtonClick(this._handleFavoriteClick);
```diff
- this._eventView.setOnFavoriteButtonClick(this._handleFavoriteClick);
+ this._eventView.setOnFavoriteButtonClick(this._handleFavoriteButtonClick);
```

2021-01-25 00:10 UTC, AlexMasterov commented on src/view/event-edit/create-offers-template.js
>          <input class="event__offer-checkbox  visually-hidden" id="event-offer-${id}-${index + 1}" type="checkbox" name="event-offer-${id}"
id="event-offer-${`id`}-${`index` + 1}"
for="event-offer-${`id`}-${`index` + 1}"

В этом шаблоне для избежания конфликта в DOM достаточно использовать `index`.

2021-01-25 02:06 UTC, AlexMasterov requested changes

2021-01-25 02:06 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +        const inputTypesListTemplate = typesList.querySelector(`#` + evt.target.htmlFor);
inputTypesList`Template`

Это не шаблон.

См. [прошлое замечание](https://github.com/htmlacademy-ecmascript/174891-big-trip-13/pull/10#discussion_r562378170).

2021-01-25 02:45 UTC, AlexMasterov commented
> Нужны пояснения и по тому, как заменять фото и описания

<details>
<summary>Покажи ответ</summary>

<details>
<summary>view/event-edit/event-edit-item.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/bdb6feb9c811d670d9afcbba61cb837fd7ab77ca/src/view/event-edit/event-edit-item.js#L143
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/bdb6feb9c811d670d9afcbba61cb837fd7ab77ca/src/view/event-edit/event-edit-item.js#L167
</details>

Обрати внимание, что род. метод [SmartView.`updateData`](https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/bdb6feb9c811d670d9afcbba61cb837fd7ab77ca/src/view/smart.js#L9-L25) вызывается без аргументов, а сам метод обновляет компонент на основе данных из свойства `this._data`, которое сейчас остается пустым (поэтому [обновление элемента не происходит](https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/bdb6feb9c811d670d9afcbba61cb837fd7ab77ca/src/view/smart.js#L10-L12)). 

Нужно научиться работать с его свойством [`this._data`](https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/bdb6feb9c811d670d9afcbba61cb837fd7ab77ca/src/view/smart.js#L6) и правильно использовать сам метод `SmartView.updateData`.

См. пример в демо проекте:
[6.1.1 Отвязываем логику показа разметки от данных](https://github.com/htmlacademy-ecmascript/taskmanager-13/commit/80257811057cd751db8e4e5ad60901bcfd79cda8)

>  Не нужно изменять напрямую (_по ссылке_) объект `point`!
</details>

2021-01-25 02:45 UTC, AlexMasterov commented
_> не разобралась с ошибкой при save_

<details>
<summary>Покажи ответ</summary>

<details>
<summary>view/event-edit/event-edit-item.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/bdb6feb9c811d670d9afcbba61cb837fd7ab77ca/src/view/event-edit/event-edit-item.js#L122
</details>

<details>
<summary>presenter/point.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/bdb6feb9c811d670d9afcbba61cb837fd7ab77ca/src/presenter/point.js#L101-L104
</details>

Обрати внимание, что `this._callback.submitForm()` (= `_handleFormSubmit`) вызывается без аргумента, но сам коллбэк `_handleFormSubmit` использует параметр `point`, значение которого таким образом оказывается `undefined` 😃

См. решение в демо проекте:
[6.1.1 Отвязываем логику показа разметки от данных](https://github.com/htmlacademy-ecmascript/taskmanager-13/commit/80257811057cd751db8e4e5ad60901bcfd79cda8) ([точнее](https://github.com/htmlacademy-ecmascript/taskmanager-13/commit/80257811057cd751db8e4e5ad60901bcfd79cda8#diff-d3bdc89dfe9d96f5cb9a37b5081c02458c200ae96df959504dedc17313a3a254L150-R150)).
</details>

2021-01-25 03:03 UTC, AlexMasterov commented
> Попробовала создать отдельные структуры для предложений (типа activeOffers и eventOffers), но только все сломала

<details>
<summary>Покажи ответ</summary>

Сейчас в первую очередь нужно научиться правильно использовать `SmartView` (или реализовать без него, по старому). Логику для `offers` лучше доработать уже после получения данных с сервера.

На мой взгляд, настоящая проблема в том, что с самого первого интенсива данные предложений для точек маршрута генерируется (случайным образом) отдельно от общего списка `offers`. В таком случае могут быть одинаковые предложения, но с разной ценой. Тогда в чате авторы курса объяснили это имитацией рыночной ситуации и даже планировали это явно учесть в ТЗ. Но с тех пор ТЗ постоянно упрощалось.

Если сейчас не учесть эту разницу с ценой одинаковых предложений, то часть выбранных предложений будет потеряно. Но этого не случиться в случае пустого списка и создания новой (и первой) точки маршрута. 

> Насколько это важно для защиты решать не мне 😃
</details>

2021-01-25 04:32 UTC, AlexMasterov commented on src/view/smart.js
> +  updateData(update, justDataUpdating) {
```diff
- updateData(update, justDataUpdating) {
+ updateData(update, justDataUpdating = false) {
```

2021-01-25 20:57 UTC, MariaSarbaj commented
Попробовала переписать основную часть, но задание упорно не поддается

2021-01-27 09:04 UTC, AlexMasterov requested changes

2021-01-27 09:17 UTC, AlexMasterov commented
> Попробовала переписать основную часть, но задание упорно не поддается

Новое решение _очень_ похоже на подход, который использовался на прошлых интенсивах, и уже тогда был признан неудачным. Предупреждаю, что он потребует отказа от `SmartView` и доработке интерфейсов в других местах проекта.

Мне нужно понять, в чем была сложность реализовать решение со `SmartView` по [коммиту из демо проекта](https://github.com/htmlacademy-ecmascript/taskmanager-13/commit/80257811057cd751db8e4e5ad60901bcfd79cda8)? (нужен свой пример?)

2021-01-28 11:17 UTC, AlexMasterov commented
👍🏻

Самое сложное позади, дальше рутина. Поторопись, можешь успеть отправить проект на защиту.

2021-01-28 11:17 UTC, merged