Обновление века (часть 2)
htmlacademy-ecmascript/174891-big-trip-13 pull request #11
Opened 2021-01-28 20:38 UTC by MariaSarbaj

---
:mortar_board: [Обновление века (часть 2)](https://up.htmlacademy.ru/ecmascript/13/user/174891/tasks/11)

2021-01-28 20:41 UTC, MariaSarbaj commented
Написала вопрос в ТГ

2021-01-29 06:04 UTC, AlexMasterov requested changes

2021-01-29 06:04 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
Сейчас при использование `flatpickr` [утекает память](https://ru.wikipedia.org/wiki/%D0%A3%D1%82%D0%B5%D1%87%D0%BA%D0%B0_%D0%BF%D0%B0%D0%BC%D1%8F%D1%82%D0%B8).

Б36

Нужно реализовать удаление элемента `flatpickr`.

> См. [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-13/blob/master/src/view/task-edit.js#L180-L189)

2021-01-29 06:04 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +import dayjs from "dayjs";
В лекциях на JS1 и JS2 просили не использовать напрямую библиотеки, а создавать модули с интерфесами из функций. 

См. [utils/date.js](https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/e25f10197e376961de6fc7a03210b04b98bf4a20/src/utils/date.js).

2021-01-29 09:37 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +          minDate: this._data.dateFrom
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106255044-88e83580-622a-11eb-974f-013c2e5aa7a3.png)
![image](https://user-images.githubusercontent.com/700213/106255201-c8168680-622a-11eb-814e-d6028f143f1b.png)

</details>

Одного `minDate` не достаточно. Для `dateFrom` следует также задать `maxDate`. 

Важно понимать, что это будет работать только для первой даты при создании `flatpickr` и после изменения одной из дат синхронизации не будет — будет возможно снова выбрать невалидную пару из дат. Поэтому такого решения недостаточно.

Для синхронизации можно использовать метод `flatpickr.set` с аргументом `minDate` и `maxDate`. Но для этого скорее всего потребуется создать два обработчика для `onChange` (вместо одного `_onDateChange`).

> См. [документацию](https://flatpickr.js.org/instance-methods-properties-elements/#methods)

2021-01-29 09:37 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +  _setFlatpickr() {
<details>
<summary>view/event-edit/event-edit-item.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b5c66c6bd8100a277616909aa543486ee4c95386/src/view/event-edit/event-edit-item.js#L158-L162
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b5c66c6bd8100a277616909aa543486ee4c95386/src/view/event-edit/event-edit-item.js#L174-L182
</details>

Д11

2021-01-29 09:37 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +    const dateTo = this.getElement().querySelector(`[name="event-end-time"]`);
**2x** this.`getElement()` 😟

В замечание по этому месту показывал, что следует сделать. (сохранить элемент в переменную, которую _переиспользовать_)

2021-01-29 09:37 UTC, AlexMasterov commented on src/utils/date.js
> +  day: 86400000
<details>
<summary>date.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b5c66c6bd8100a277616909aa543486ee4c95386/src/utils/date.js#L3-L6
</details>

Duration`s`

[`Б 7`](https://up.htmlacademy.ru/ecmascript/13/criteries#b7)
> Перечисления названы существительными в единственном числе

`hour`
`day`

> Значения перечислений объявлены как константы

2021-01-29 09:37 UTC, AlexMasterov commented on src/utils/date.js
> +const formatEventDuration = (finish, start) => {
<details>
<summary>formatEventDuration</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b5c66c6bd8100a277616909aa543486ee4c95386/src/utils/date.js#L16-L26
</details>

Вместо `switch` лучше использовать `if` с таким же быстрым `return` (без `else`).

В целом странное решение, особенно с учетом примеров в чате, но тоже работает 😃

2021-01-29 09:37 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +    this.updateData({
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/pull/11#discussion_r566596410

Замечание актуально.

2021-01-29 09:37 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +import "../../../node_modules/flatpickr/dist/flatpickr.min.css";
😕

```diff
- import "../../../node_modules/flatpickr/dist/flatpickr.min.css";
+ import "flatpickr/dist/flatpickr.min.css";
```

> `Webpack` разберется

2021-01-29 09:37 UTC, AlexMasterov commented on src/view/event-item/event-item.js
> +                  <p class="event__duration">${eventDuration}</p>
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/106258096-75d76480-622e-11eb-809d-69bce0784ed0.png)

</details>

См. внимательно в ТЗ [формат для времени продолжительности](https://up.htmlacademy.ru/ecmascript/13/project/big-trip#tripPoint).

2021-01-29 09:59 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +
См. ТЗ:
> После сохранения изменений точка маршрута располагается в списке точек маршрута в порядке определённом текущей сортировкой (по дате, по длительности или по стоимости)

Желательно реализовать перерисовку списка в этом задание.

2021-01-29 14:42 UTC, MariaSarbaj commented on src/view/event-edit/event-edit-item.js
> +
Оставила на следующее задание

2021-01-29 14:52 UTC, AlexMasterov approved these changes

2021-01-29 14:52 UTC, AlexMasterov commented on src/utils/date.js
>  const formatEventDuration = (finish, start) => {
<details>
<summary>utils/date.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/5e5b3f57c3a999b920757941b90af905badd0090/src/utils/date.js#L17-L29
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/5e5b3f57c3a999b920757941b90af905badd0090/src/utils/date.js#L31-L44
</details>

Пож. верни, как было 🙈

2021-01-29 14:52 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +    this.updateData = this.updateData.bind(this);
`.bind` нужно делать на обработчики, в которых используется `this`: `_onDateFromChange`, `_onDateToChange` 😃

2021-01-29 14:52 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +  _removeFlatpickrFrom() {
`_removeFlatpickrTo`
`_removeFlatpickrFrom`

Д8

Нужно поднять выше обработчиков.

2021-01-29 14:52 UTC, merged

2021-01-29 14:53 UTC, MariaSarbaj commented on src/utils/date.js
>  const formatEventDuration = (finish, start) => {
Если вернуть все как было, не знаю, как встроить буквы d, h, m 🤷‍♀️