Структуры и данные
htmlacademy-ecmascript/174891-big-trip-13 pull request #4
Opened 2020-12-12 18:17 UTC by MariaSarbaj

2020-12-14 01:01 UTC, AlexMasterov requested changes

2020-12-15 20:12 UTC, AlexMasterov requested changes

2020-12-15 20:12 UTC, AlexMasterov commented on src/view/event-item/event-item.js
> +  const eventOffers = offers !== null ? renderTripEventOffers(offers) : ``;
`offers !== null` 🤔

`offers` — это массив, который может быть пустым, но никак не `null`.

2020-12-15 20:12 UTC, AlexMasterov commented on src/view/event-edit/event-edit.js
> +const createEditPointTemplate = (point) => {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/102267116-78098c00-3f2a-11eb-9cc9-5e4957fc8235.png)

</details>

`undefined` в названиях предложений.

Нужно исправить.

> Дорабатывать логику `offers` будем в след. заданиях или при получение данных с сервера

2020-12-15 20:12 UTC, AlexMasterov commented on src/view/event-edit.js
> +  const renderTripTypesList = (types) => {
Замечание актуально.

2020-12-15 20:25 UTC, AlexMasterov requested changes

2020-12-15 20:25 UTC, AlexMasterov commented on src/view/event-item/event-item.js
> +                <h3 class="event__title">${eventTypeUpperCase} to ${destination.name}</h3>
<details>
<summary>markup/list.html</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/ce410ebb47a452d51e99f896aec80cf26b29918c/markup/list.html#L102
</details>

У тебя используется старая разметка 🤔

`to`/`in` нет в разметки нового макета и требование к ним нему убрали из ТЗ. Нужно удалить.

2020-12-17 01:13 UTC, AlexMasterov requested changes

2020-12-17 01:13 UTC, AlexMasterov commented on src/view/event-edit/event-edit.js
> +import {CITIES} from "../../mock/point";
Вместо `CITIES` нужно создать массив `destinations` с объектами, структура которых которые позволяют хранить информацию о направление: название, описание и фотографии. 

Структура должна хранить эти значения в удобных для использования типах, а сами значения должны помогать в реализации (и тестирвоания) ТЗ. (логика отображения уже реализована, поэтому их содержание уже неважно)

Такая структура [`destination`](https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/ce410ebb47a452d51e99f896aec80cf26b29918c/src/mock/point.js#L111-L115) уже есть — можно использовать её для генерации объектов или создать их вручную.

> [`destination`](https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/ce410ebb47a452d51e99f896aec80cf26b29918c/src/mock/point.js#L111-L115) в данных точки маршрута — это _копия_ структуры из общего списка назначений `destinations`, который был выбран и сохранен в данных точки маршрута

Этот массив `destinations` нужно передать функции `createEditPointTemplate` через доп. аргумент (в модуле `main.js`), и использовать внутри для генерации разметки.

2020-12-17 01:14 UTC, AlexMasterov commented on src/view/event-edit/event-edit.js
> +import {CITIES} from "../../mock/point";
<details>
<summary>Объясни, что нужно сделать</summary>

Вместо `CITIES` нужно создать массив `destinations` с объектами, структура которых которые позволяют хранить информацию о направление: название, описание и фотографии. 

Структура должна хранить эти значения в удобных для использования типах, а сами значения должны помогать в реализации (и тестирвоания) ТЗ. (логика отображения уже реализована, поэтому их содержание уже неважно)

Такая структура [`destination`](https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/ce410ebb47a452d51e99f896aec80cf26b29918c/src/mock/point.js#L111-L115) уже есть — можно использовать её для генерации объектов или создать их вручную.

> [`destination`](https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/ce410ebb47a452d51e99f896aec80cf26b29918c/src/mock/point.js#L111-L115) в данных точки маршрута — это _копия_ структуры из общего списка назначений `destinations`, который был выбран и сохранен в данных точки маршрута

Этот массив `destinations` нужно передать функции `createEditPointTemplate` через доп. аргумент (в модуле `main.js`), и использовать внутри для генерации разметки.
</details>

2020-12-17 10:39 UTC, MariaSarbaj commented
Надеюсь, правильно поняла про destinations и исправила

2020-12-17 10:45 UTC, AlexMasterov commented
> Надеюсь, правильно поняла про destinations и исправила

Всё отлично.
Прошу смелее спрашивать и переспрашивать, чем повторять ошибки делать "наугад" 😃

2020-12-17 10:45 UTC, merged