presenter
htmlacademy-ecmascript/174891-big-trip-13 pull request #8
Opened 2021-01-11 07:39 UTC by MariaSarbaj

Пока только presenter, чтобы разобраться с ним. Без датабиндинга

2021-01-11 07:41 UTC, MariaSarbaj commented
Про не пройденный linter знаю, опять же, точки с запятыми потом расставлю

2021-01-11 22:38 UTC, AlexMasterov requested changes

2021-01-11 22:38 UTC, AlexMasterov commented on src/main.js
> +  eventEditComponent.setOnFormSubmit(() => {
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b82439a244480a62baa9f52fee6bb47566fb7e6a/src/main.js#L47
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b82439a244480a62baa9f52fee6bb47566fb7e6a/src/main.js#L52
</details>

set`On` / set`Handler`

Нужно определиться с форматом названия для метода установки обработчика и придерживаться во всём проекте.

2021-01-11 22:38 UTC, AlexMasterov commented on src/presenter/list.js
> +import TripInfoSection from "../view/trip-info-section/trip-info-section";
```
'TripInfoSection' is defined but never used
```
Б15

2021-01-11 22:38 UTC, AlexMasterov commented on src/presenter/list.js
> +  render(points, container) {
```
'container' is defined but never used. Allowed unused args must match /^_/u
```

Б15

2021-01-11 22:38 UTC, AlexMasterov commented on src/presenter/list.js
> +export default class pageLayout {
`page`Layout

[`Б 6`](https://up.htmlacademy.ru/ecmascript/13/criteries#b6)
> Классы названы английскими существительными. **Название класса начинается с заглавной буквы**

2021-01-11 22:38 UTC, AlexMasterov commented on src/presenter/list.js
> +export default class pageLayout {
`pageLayout` !== src/presenter/`list`.js

[`Б 27`](https://up.htmlacademy.ru/ecmascript/13/criteries#b27)
> Название модуля соответствует его содержимому

> Например, если в модуле лежит класс `GameView`, то и имя модуля должно быть `game-view`.js

2021-01-11 22:38 UTC, AlexMasterov commented on src/presenter/list.js
> +export default class pageLayout {
`pageLayout` 🤔

См. задание:

> Создайте класс для презентера маршрута и класс для презентера точки маршрута (например,**`Trip`** и Point)

2021-01-11 22:38 UTC, AlexMasterov commented on src/presenter/list.js
> +  const eventEditComponent = new EventEditItemView(point, destinations);
<details>
<summary>presenter/list.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b82439a244480a62baa9f52fee6bb47566fb7e6a/src/presenter/list.js#L26-L27
</details>

event`Component`
eventEdit`Component`

Желательно в название переменных, которые хранят экземпляры `views`, вместо `Component` использовать суффикс `View`.

> `Component` — рудимент с прошлых интенсивов

2021-01-11 22:38 UTC, AlexMasterov commented on src/presenter/list.js
> +    if (evt.key === `Escape` || evt.key === `Esc`) {
`Escape`
`Esc`

Б5

Для хранения постоянных значений ключей клавиатуры, которые используются в логике, создай перечисление (= `KeyboardKey`).

<details>
<summary>presenter/list.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b82439a244480a62baa9f52fee6bb47566fb7e6a/src/presenter/list.js#L19
</details>

Для проверки на `evt.key` создай предикат-функцию, например, `isEscapeKey`.

2021-01-11 22:38 UTC, AlexMasterov commented on src/presenter/list.js
> +      renderElement(this._container, this._noEventView, RenderPosition.BEFOREEND);
```diff
- renderElement(this._container, this._noEventView, RenderPosition.BEFOREEND);
+ renderElement(this._container, new NoEventView());
```
<details>
<summary>presenter/list.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b82439a244480a62baa9f52fee6bb47566fb7e6a/src/presenter/list.js#L46
</details>

```diff
- this._noEventView = new NoEventView();
```

2021-01-11 22:38 UTC, AlexMasterov commented on src/view/event-edit/event-edit-item.js
> +    this._onFormSubmit = this._onFormSubmit.bind(this);
<details>
<summary>view/event-item/event-item.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b82439a244480a62baa9f52fee6bb47566fb7e6a/src/view/event-item/event-item.js#L61
</details>

Нужно так же исправить:

```diff
- this._onRollupButtonClick = this._editClickHandler.bind(this);
+ this._onRollupButtonClick = this._onRollupButtonClick.bind(this);
```
> \+ название метода-обработчика

2021-01-11 22:38 UTC, AlexMasterov commented on src/presenter/list.js
> +  renderElement(container, eventComponent, RenderPosition.BEFOREEND);
```diff
- renderElement(container, eventComponent, RenderPosition.BEFOREEND);
+ renderElement(container, eventComponent);
```

2021-01-11 22:39 UTC, AlexMasterov requested changes

2021-01-11 22:39 UTC, AlexMasterov commented on src/presenter/list.js
> +const renderEvent = (container, point) => {
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b82439a244480a62baa9f52fee6bb47566fb7e6a/src/presenter/list.js#L29
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b82439a244480a62baa9f52fee6bb47566fb7e6a/src/presenter/list.js#L34
</details>

set`On` / set`Handler`

Нужно определиться с форматом названия для метода установки обработчика и придерживаться во всём проекте.

2021-01-11 22:45 UTC, AlexMasterov requested changes

2021-01-11 22:45 UTC, AlexMasterov commented on src/presenter/list.js
> +import {destinations} from "../mock/point";
`destinations`

См. задание:

> Конструктор презентера **должен принимать** необходимые данные

Нужно передавать данные в качестве аргументов при создание экземпляра класса (объекта) презентера (сейчас из модуля `main.js`) и получать их внутри из параметров его конструктора.

> Прямого импорта и использования тестовых данных  в модули компонентов быть не должно

2021-01-11 22:51 UTC, AlexMasterov requested changes

2021-01-11 22:51 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/utils.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/b82439a244480a62baa9f52fee6bb47566fb7e6a/src/utils/utils.js#L36-L52
</details>

🤔

<details>
<summary>Покажи на что лучше исправить</summary>

См. [ChildNode.`replaceWith`](https://developer.mozilla.org/ru/docs/Web/API/ChildNode/replaceWith).

<details>
<summary>Реализация .replaceWith в Chromium</summary>

Этот метод сам проверяет наличие `ParentNode` (и выбрасывает исключение):

[third_party/blink/renderer/core/dom/`node`.cc](https://source.chromium.org/chromium/chromium/src/+/refs/tags/85.0.4183.40:third_party/blink/renderer/core/dom/node.cc;l=937-941;drc=c5f01d3e7fcd4d376f593120dd8010ac84155fae):

```cpp
void Node::ReplaceWith(const HeapVector<NodeOrStringOrTrustedScript>& nodes,
                       ExceptionState& exception_state) {
  Node* parent = parentNode();
  if (!parent)
    return;
```
```cpp
ContainerNode* Node::parentNode() const {
  return IsShadowRoot() ? nullptr : ParentOrShadowHostNode();
}
```
[third_party/blink/renderer/core/dom/`element`.h](https://source.chromium.org/chromium/chromium/src/+/refs/tags/85.0.4183.40:third_party/blink/renderer/core/dom/element.h;l=1239-1241):
```cpp
inline Element* Node::parentElement() const {
  return DynamicTo<Element>(parentNode());
}
```
</details>

Для нашего случая будет достаточно этого:

```js
export const replace = (newChild, oldChild) => {
  if (oldChild instanceof Abstract) {
    oldChild = oldChild.getElement();
  }

  if (newChild instanceof Abstract) {
    newChild = newChild.getElement();
  }

  if (oldChild === null || newChild === null) {
    throw new Error(`Can't replace unexisting elements`);
  }

  oldChild.replaceWith(newChild);
};
```
> Актуальный метод в демо проекте нарушает [`Д7`](https://up.htmlacademy.ru/ecmascript/13/criteries#d7) и [`Д10`](https://up.htmlacademy.ru/ecmascript/13/criteries#d10)
</details>

2021-01-14 00:50 UTC, AlexMasterov requested changes

2021-01-14 00:50 UTC, AlexMasterov commented on src/presenter/point.js
> +const isEscapeKey = (evt) => evt.key === `Escape` || evt.key === `Esc`;
`Escape`
`Esc`

Б5

См. https://github.com/htmlacademy-ecmascript/174891-big-trip-13/pull/8#discussion_r555382637:
> Для хранения постоянных значений ключей клавиатуры, которые используются в логике, создай перечисление (= `KeyboardKey`)

2021-01-14 00:50 UTC, AlexMasterov commented on src/main.js
> +tripEvents.render(points);
Пож. переделай названия по примеру демо проекта:

```js
const tripPresenter = new TripPresenter(eventList);
tripPresenter.init(points, destinations, /** offers */);
``` 

<details>
<summary>presenter/point.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/518b4cdb42b679186bfba827112203b4c59950e8/src/presenter/point.js#L4
</details>

```diff
- import {destinations} from "../mock/point";
```

2021-01-14 00:50 UTC, AlexMasterov commented on src/presenter/point.js
> +    if (isEscapeKey) {
🤔
```diff
- if (isEscapeKey) {
+ if (isEscapeKey(evt)) {
```

2021-01-14 00:50 UTC, AlexMasterov commented on src/presenter/point.js
> +    document.removeEventListener(`keydown`, this._onFormEscKeyDown);
<details>
<summary>presenter/point.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/518b4cdb42b679186bfba827112203b4c59950e8/src/presenter/point.js#L35-L36
https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/518b4cdb42b679186bfba827112203b4c59950e8/src/presenter/point.js#L46-L47
</details>

В текущем варианте можно вложить `document.removeEventListener` в `_replaceEditToEvent`.

2021-01-14 00:50 UTC, AlexMasterov commented on src/presenter/point.js
> +    this._point = point;
Добавь в конструктор:

```js
this._point = [];
```

2021-01-14 00:50 UTC, AlexMasterov commented on src/presenter/point.js
> +export default class Point {
[`Д 8`](https://up.htmlacademy.ru/ecmascript/13/criteries#d8)
> Методы внутри классов упорядочены

<details>
<summary>presenter/point.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/518b4cdb42b679186bfba827112203b4c59950e8/src/presenter/point.js#L62-L74
</details>

> Методы класса
> Приватные методы

<details>
<summary>presenter/point.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/518b4cdb42b679186bfba827112203b4c59950e8/src/presenter/point.js#L32-L38
</details>

> Обработчики событий

2021-01-14 00:50 UTC, AlexMasterov commented on src/presenter/trip.js
> +        this._pointPresenter.init(point);
<details>
<summary>presenter/trip.js</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/518b4cdb42b679186bfba827112203b4c59950e8/src/presenter/trip.js#L13
</details>

Нужно удалить.

Вместо следует создавать `PointPresenter` для каждой точки маршрута (`point`), и сохранять их в удобную для работы структуру, например, `{}` или [`Map`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map).

> См. [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-13/commit/69f03e890f8a9a280f799df5a46e7d1b9bedbda7) + [другой](https://github.com/htmlacademy-ecmascript/taskmanager-13/commit/e82dabdc65414cb6f15d45fdcb4e0b82d81d5e4f#diff-cb96f5f92717ed5e803678dbe17503fa4f37e20c409a622c9353969a7f25885c)

2021-01-14 00:50 UTC, AlexMasterov commented on src/utils/utils.js
> +  oldChild.replaceChild(newChild);
См. внимательно https://github.com/htmlacademy-ecmascript/174891-big-trip-13/pull/8#discussion_r555389496:

```diff
- oldChild.replaceChild(newChild);
+ oldChild.replaceWith(newChild);
```

2021-01-14 00:50 UTC, AlexMasterov commented on src/view/event-item/event-item.js
[`Д 8`](https://up.htmlacademy.ru/ecmascript/13/criteries#d8)
> Методы внутри классов упорядочены

Нужно исправить порядок методов в классе.

2021-01-14 00:50 UTC, AlexMasterov commented on src/view/event-item/event-item.js
>      this._eventPoint = point;
```diff
- this._eventPoint = point;
+ this._point = point;
```

2021-01-14 00:50 UTC, AlexMasterov commented on src/view/event-item/event-item.js
> +  setOnFavoriteClick(callback) {
```diff
- setOnFavoriteClick(callback) {
+ setOnFavoriteButtonClick(callback) {
```

2021-01-14 00:50 UTC, AlexMasterov commented on src/view/event-item/event-item.js
> +  _onFavoriteClick(evt) {
```diff
- _onFavoriteClick(evt) {
+ _onFavoriteButtonClick(evt) {
```

2021-01-14 00:50 UTC, AlexMasterov commented on src/presenter/trip.js
> +    this._handlePointChange = this._handlePointChange.bind(this);
Нужно доработать.

> См. [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-13/commit/5581c588e0b2af72a9d49c59815f8de9770b1ad7)

2021-01-14 01:00 UTC, AlexMasterov requested changes

2021-01-14 01:08 UTC, AlexMasterov requested changes

2021-01-14 01:08 UTC, AlexMasterov commented on src/presenter/trip.js
> +  render(points) {
Добавь в конструктор:

```js
this_points = [];
```
А в `render`:

```js
this_points = points.slice();
```
Потребуется для сортировки и фильтрации.

> См. внимательно [пример в демо](https://github.com/htmlacademy-ecmascript/taskmanager-13/commit/e34464457155336bf48ab8b65a09aab18ed7d2fa)

2021-01-15 17:52 UTC, MariaSarbaj commented
Вроде реализовала открытие одной формы и добавления в избранное, но нужны пояснения по переносу destinations в класс и как правильно переделать pointPresenter для каждой точки. Потому что при попытке это сделать на этом все сломалось:)

2021-01-16 07:05 UTC, AlexMasterov requested changes

2021-01-16 07:05 UTC, AlexMasterov commented on src/utils/utils.js
> +export const updateItem = (items, update) => {
<details>
<summary>updateItem</summary>

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/9907cbbee9691bfe6ccd95fff7a43d88f2b29907/src/utils/utils.js#L62
</details>

```diff
- export const updateItem = (items, update) => {
+ export const updateItemById = (items, update) => {
```

2021-01-16 07:17 UTC, AlexMasterov requested changes

2021-01-16 07:17 UTC, AlexMasterov commented on src/presenter/trip.js
> +        this._pointPresenter.init(point);
См. внимательно [прошлое замечание](https://github.com/htmlacademy-ecmascript/174891-big-trip-13/pull/8#discussion_r556968483).

<details>
<summary>Покажи наглядно, что нужно сделать</summary>

<details>
<summary>mock/point.js</summary>

```js
// mock/point.js
const generateId = () => Date.now() + parseInt(Math.random() * 10000, 10);
```

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/9907cbbee9691bfe6ccd95fff7a43d88f2b29907/src/mock/point.js#L149-L150

```diff
+ id: generateId(),
```
</details>

<details>
<summary>presenter/trip.js</summary>

```js
// presenter\trip.js (Trip)
_renderPoint(point) {
  const pointPresenter = new PointPresenter(this._container, this._handlePointChange, this._handleModeChange);
  pointPresenter.init(point, this._destinations);
  this._pointPresenter[point.id] = pointPresenter;
}
```

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/9907cbbee9691bfe6ccd95fff7a43d88f2b29907/src/presenter/trip.js#L38

```diff
- this._pointPresenter[updatedPoint.id].render(updatedPoint); 
+ this._pointPresenter[updatedPoint.id].init(updatedPoint, this._destinations);
```

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/9907cbbee9691bfe6ccd95fff7a43d88f2b29907/src/presenter/trip.js#L21

```diff
- this._pointPresenter = new PointPresenter(this._container, this._handlePointChange, this._handleModeChange());
```

https://github.com/htmlacademy-ecmascript/174891-big-trip-13/blob/9907cbbee9691bfe6ccd95fff7a43d88f2b29907/src/presenter/trip.js#L31

```diff
- this._pointPresenter.init(point);
+ this._renderPoint(point);
```
</details>
</details>

2021-01-16 07:20 UTC, AlexMasterov commented on src/presenter/trip.js
> +  render(points) {
```diff
- render(points) {
+ init(points, destinations) {
```

2021-01-18 20:33 UTC, AlexMasterov commented
Для этого задания код стал рабочим 😃

2021-01-18 20:33 UTC, merged